name: check-code

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build the docker-compose stack
        run: docker-compose up -d

      - name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash

      - name: Check
        run: |
          docker-compose exec -T xrt_usdt_app make test lint mypy
